# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3353c0cd9233f561b6d7c33f9bd246e0bacdea4d772f60db55aab971d171520c6d4c9a0350d8f198e85cc4c316e673d6bc58cf0e7750596f844728356b876eae

test:
  secret_key_base: d84a5c7b3f67d347fd34ca67f9808417691f381ce9879c1a39c47cfff27074e5ecf929df77e5729ef4279c263abb75c281c546ff76d8db43227e5ba3234059b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
